version: '3.4'

services:
  apimysqldocker:
    image: ${DOCKER_REGISTRY-}apimysqldocker
    container_name: products.api
    build:
      context: .
      dockerfile: ApiMySqlDocker/Dockerfile
    depends_on:
      - database
    ports:
      - "5000:80"
    restart: always
    environment:
      - ASPNETCORE_ENVIROMENT=Development
  
  database:
    image: mysql
    container_name: mysqldb
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - dbmysql-volume:/var/lib/mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: hen
      MYSQL_PASSWORD: senha
      MYSQL_DATABASE: productsdb

volumes:
  dbmysql-volume: